name: Release

on:
  push:
    branches:
      - master
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: hello-lib
          path: packages/hello-lib
      - run: echo '::set-output name=releases_created::1'
      - run: echo 'releases_created=>${{ steps.release.outputs.releases_created }}'
      - uses: actions/checkout@v3
        #if: ${{ steps.release.outputs.releases_created }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'
          scope: '@atinc'
        #if: ${{ steps.release.outputs.releases_created }}
      #- run: npm install
      - run: npm ci #必须的有package-lock.json文件
        #if: ${{ steps.release.outputs.releases_created }}
      - run: npx nx build hello-lib
        #if: ${{ steps.release.outputs.releases_created }}
      ###- run: npx nx publish hello-lib
      - run: npm publish
        working-directory: ./dist/packages/hello-lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #if: ${{ steps.release.outputs.releases_created }}