name: Release

on:
  push:
    branches:
      - master
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: hello-lib
          path: packages/hello-lib
      - run: echo '::set-output name=releases_created::true'
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.releases_created }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@atinc'
        if: ${{ steps.release.outputs.releases_created }}
      - run: npm ci
        if: ${{ steps.release.outputs.releases_created }}
      - run: npx nx build hello-lib
        if: ${{ steps.release.outputs.releases_created }}
      - run: npx nx publish
        working-directory: ./dist/packages/hello-lib
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.release.outputs.releases_created }}